{% set name = "pyopengl" %}
{% set version = "3.1.9" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyopengl-{{ version }}.tar.gz
  sha256: 28ebd82c5f4491a418aeca9672dffb3adbe7d33b39eada4548a5b4e8c03f60c8

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - rmdir /s /q %SP_DIR%\OpenGL\DLLS  # [win]

requirements:
  host:
    - python
    - pip
    - setuptools >=42.0
    - wheel
  run:
    - python
  run_constrained:
    - numpy >=2  # [py>=39]
    - numpy <2   # [py<39]

# Some tests only apply to certain platforms. For instance, Windows is not expected to have an X server so GLX tests
# don't make sense there.
test:
  imports:
    - OpenGL
    - OpenGL.acceleratesupport
    - OpenGL.arrays
    - OpenGL.constants
    - OpenGL.contextdata
    - OpenGL.converters
    - OpenGL.error
    - OpenGL.extensions
    - OpenGL.images
    - OpenGL.latebind
    - OpenGL.lazywrapper
    - OpenGL.logs
    - OpenGL.osmesa  # [not win]
    - OpenGL.platform
    - OpenGL.version
    - OpenGL.wrapper
    - OpenGL.AGL
    - OpenGL.EGL     # [not win]
    - OpenGL.GL
    - OpenGL.GL.feedback
    - OpenGL.GL.framebufferobjects
    - OpenGL.GL.glget
    - OpenGL.GL.images
    - OpenGL.GL.pointers
    - OpenGL.GL.selection
    - OpenGL.GL.shaders
    - OpenGL.GL.vboimplementation
    - OpenGL.GLE
    - OpenGL.GLES1   # [not win]
    - OpenGL.GLES2   # [not win]
    - OpenGL.GLES3   # [not win]
    - OpenGL.GLU
    - OpenGL.GLUT
    - OpenGL.GLX     # [not win]
    # Needs the Tk OpenGL Widget (togl).
    - OpenGL.Tk      # [not win]
    - OpenGL.WGL
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://mcfletch.github.io/pyopengl/
  license: LicenseRef-pyopengl
  license_family: Other
  license_file: license.txt
  summary: Standard OpenGL bindings for Python
  description: |
    PyOpenGL is the most common cross platform Python binding to OpenGL and related APIs.
    The binding is created using the standard ctypes library, and is provided under a liberal BSD-style Open-Source license.
  doc_url: https://mcfletch.github.io/pyopengl/documentation/index.html
  dev_url: https://github.com/mcfletch/pyopengl

extra:
  recipe-maintainers:
    - almarklein
    - mcfletch
    - tadeu
