{% set name = "pyopengl" %}
{% set version = "3.1.9" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyopengl-{{ version }}.tar.gz
  sha256: 28ebd82c5f4491a418aeca9672dffb3adbe7d33b39eada4548a5b4e8c03f60c8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools >=42.0
    - wheel
  run:
    - python

test:
  imports:
    - OpenGL.GL
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://mcfletch.github.io/pyopengl/
  license: LicenseRef-pyopengl
  license_family: Other
  license_file: license.txt
  summary: Standard OpenGL bindings for Python
  description: |
    PyOpenGL is the most common cross platform Python binding to OpenGL and related APIs.
    The binding is created using the standard ctypes library, and is provided under a liberal BSD-style Open-Source license.
  doc_url: https://mcfletch.github.io/pyopengl/documentation/index.html
  dev_url: https://github.com/mcfletch/pyopengl

extra:
  recipe-maintainers:
    - almarklein
    - mcfletch
    - tadeu
