{% set name = "pyopengl" %}
{% set version = "3.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyOpenGL-{{ version }}.tar.gz
  sha256: eef31a3888e6984fd4d8e6c9961b184c9813ca82604d37fe3da80eb000a76c86

build:
  script: pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  number: 0
  skip: true # [win] pyopengl repacks opengl on windows.

requirements:
  host:
    - setuptools
    - python
    - pip
    - wheel
  run:
    - python

test:
  imports:
    - OpenGL
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mcfletch/pyopengl
  license: BSD-like # no spdx match
  license_family: Other
  license_file: license.txt
  summary: Standard OpenGL bindings for Python
  doc_url: https://mcfletch.github.io/pyopengl/documentation/index.html
  dev_url: https://github.com/mcfletch/pyopengl

extra:
  recipe-maintainers:
    - almarklein
    - mcfletch
    - tadeu
