travis:
  secure:
    BINSTAR_TOKEN: fRtLmCZ/7SjaHU6HzHrNlMVV2H53CwGqIGTCL4xdVEC77eVGLUfAmwVed2RgujtR43FPhjgqOUKnlr1qTtAEbUlhSkwLvnwRZ5vKwCgYKKH8F1Kpq5BcJFvz7ivpBXYZYA3bSYPunU1Pyl3FGBEZ7SSqK7EWDmy+G1jh3H1mxaGbVOjDYMFebI997+f1P32Q4rl3/fbwHB5RIyxUIuX9Kc6zldxAncUk0okrRroirerYK2At0mLasrxi8lLP/MRSFUmKIDHaT+SX5uQddaYnmT4CY+hnBNYwuaHSYXgOsOIUNTMiq5s0JgSigfTYgo+OJ+rH5SS3YIpHSpJJwEUVX5rCzyNLKsIbWY2cgC1K9qPuV0WWqQFaGF1rGWUGn59xI+yi02MeBmXCTXeNnXohTBrFs3t9CgGHtt1SHIqxlhqPw9Vb3mwP+Jpit9s3aFR3Qjk1zFvw3qxTkpwoy73xqfL+Ji1Bw7TGAX04yFcMWYzS2pMDfZCAs3/hBPhctFyaBDNkE8TwbKdrB8p9fWbxC0UfCqSf1D8H+TCwkS44z4YkH5NWbbnUjmPSaFM1UsyBmdOd0pGzTqMfynsaBiZlILBz9zZb9MOqhRbS8Y4MzeBtc3QyFG0OfMCRUit8i3G3HNHrzJ5T5p1HTodbwxx6oZA1mKZO7FfSx6DEyOObmuk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
